services:
    twig_extension.tangoman_pagination:
        class: TangoMan\PaginationBundle\Twig\Extension\PaginationExtension
        public: false
        arguments: ["@twig"]
        tags:
            - { name: twig.extension }
